# DGeyserMenuFlux-Folia 配置文件
settings:
  # 调试模式
  debug: false

  # 默认菜单
  default-menu: "main"

  # 热重载设置
  hot-reload:
    enabled: true
    check-interval: 2

# Folia 特定设置
folia:
  scheduler:
    inventory-scheduler: "entity"
    config-scheduler: "global"
    async-pool-size: 4

  performance:
    batch-size: 50
    cache-expiry: 300
    max-concurrent-operations: 1000
