name: DGeyserMenuFlux-Folia
version: 1.0.2
main: com.fluxcraft.dGeyserMenuFlux.DGeyserMenuFlux
api-version: "1.21"
folia-supported: true
description: "支持Folia的跨时代多版本菜单插件"
author: FluxCraft

softdepend: [floodgate, PlaceholderAPI]

commands:
  dgeysermenu:
    description: "打开菜单系统"
    usage: "/<command> open <菜单名> [玩家]"
    permission: dgeysermenu.use
    aliases: [dgm]
  getmenuclock:
    description: "获取菜单钟表"
    usage: "/<command>"
    permission: dgeysermenu.admin
    aliases: [menuclock]

permissions:
  dgeysermenu.use:
    description: "允许使用基础菜单功能"
    default: true

  dgeysermenu.reload:
    description: "允许重载插件配置"
    default: op

  dgeysermenu.admin:
    description: "管理员权限"
    default: op
